language: cpp

add-ons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

script:
  - mkdir build && cd build
  - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 cmake  -DCOVERAGE=1 ..
  - make
  - make test

after_success:
  - coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*"
