language: cpp
dist: xenial

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get update && sudo apt-get install -y libeigen3-dev

script:
  - mkdir build && cd build
  - cmake  -DCOVERAGE=1 ..
  - make
  - make test

after_success:
  - coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*"
